config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :lots, only: %i[index show new create edit update] do
    resources :questions, only: %i[new create show] do
      post 'block_by_cpf', on: :member
      resources :answers, only: %i[new create]
      get 'hidden', on: :member
      get 'visible', on: :member
    end
    resources :favorites, only: %i[create destroy]
    resources :bids, only: %i[new create]
    resources :lot_items, only: %i[new create destroy] do
      delete 'remove', on: :member
    end
    get 'expired', on: :collection
    post 'approved', on: :member
    get 'pending', on: :collection
    post 'pending_approval', on: :member
    get 'successfull_bids', on: :collection
    post 'bid_on_lot', on: :member
  end

  resources :product_categories, only: %i[index new create]

  resources :items, only: %i[index new create show edit update] do
    get 'search', on: :collection
  end

  resources :blocked_cpfs, only: %i[index new create]

  resources :users, only: %i[show edit update]

  namespace :api do
    namespace :v1 do
      resources :lots, only: %i[show index create update destroy]
    end
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :product_category

  has_one :lot_item
  has_one :lot, through: :lot_item

  has_one_attached :image

  validates :name, :description, :weight, :height, :depth, :width, presence: true

  validates :weight, :height, :width, :depth, numericality: { greater_than: 0 }

  before_validation :generate_code, :set_default_values

  validate :validate_image_extension

  def validate_image_extension
    return unless image.attached? && !image.content_type.in?(%w[image/jpeg image/png image/webp])

    errors.add(:image, 'deve ser um arquivo JPEG, PNG ou WebP')
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase
  end

  def set_default_values
    self.name ||= name_was
    self.description ||= description_was
    self.weight ||= weight_was
    self.height ||= height_was
    self.depth ||= depth_was
    self.width ||= width_was
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update]
  before_action :authenticate_user!, only: %i[new search show edit]
  before_action :check_admin_user, only: [:new]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @product_categories = ProductCategory.all
  end

  def create
    @item = Item.new(set_params)
    @product_categories = ProductCategory.all

    if @item.save
      redirect_to @item, notice: 'Produto cadastrado com sucesso'
    else
      flash.now[:alert] = 'Houve um problema para cadastrar o produto'
      render 'new'
    end
  end

  def edit
    @product_categories = ProductCategory.all
  end

  def update
    if @item.update(set_params)
      redirect_to @item, notice: 'Produto atualizado com sucesso'
    else
      flash.now[:notice] = 'Não foi possível atualizar o produto'
      render 'edit'
    end
  end

  def show
    @product_category = @item.product_category.name
  end

  def search
    @query = params[:query]
    @items_code = Item.where('code LIKE ?', "%#{@query}%")
                      .or(Item.where('name LIKE :query', query: "%#{@query}%"))
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_params
    params.require(:item).permit(:name,
                                 :description,
                                 :weight,
                                 :height,
                                 :depth,
                                 :width,
                                 :code,
                                 :product_category_id,
                                 :image)
  end

  def check_admin_user
    return if current_user.admin?

    redirect_to root_path, alert: 'Você não tem permissão para acessar esta página'
  end
end

app/views/items/_form.html.erb
<%= form_with model: @item, data: { turbo: false } do |f| %>

    <div class="input-group input-group-default mt-4">
      <%= f.label :name, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %><br />
      <%= f.text_field :name, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default", autofocus: true %>
    </div>

    <div class="input-group input-group-default mt-4">
      <%= f.label :description, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %><br />
      <%= f.text_field :description, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
    </div>

    <div class="input-group input-group-default mt-4">
      <%= f.label :weight, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %><br />
      <%= f.number_field :weight, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
    </div>

    <div class="input-group input-group-default mt-4">
      <%= f.label :height, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %><br />
      <%= f.number_field :height, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
    </div>

    <div class="input-group input-group-default mt-4">
      <%= f.label :depth, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %><br />
      <%= f.number_field :depth, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
    </div>

    <div class="input-group input-group-default mt-4">
      <%= f.label :width, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %><br />
      <%= f.number_field :width, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
    </div>

    <div class="input-group input-group-default mt-4">
      <%= f.label :product_category_id, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %><br />
      <% if @product_categories %>
        <%= f.collection_select :product_category_id, @product_categories, :id, :name, {}, { class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" } %>
      <% end %>
    </div>

    <div class="input-group input-group-default mt-4">
      <%= f.label :image, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-default"  %>
      <%= f.file_field :image, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
    </div>

    <div class="d-grid">
      <%= f.submit 'Salvar', class: "btn btn-success mb-3 mt-5 btn-default"  %><br />
    </div>
  <% end %>

app/views/items/_item.html.erb
<h3 class="mb-5 ms-2 text-success"><strong> <%= item.name %> </strong></h3>
<p><strong><%= Item.human_attribute_name(:code) %>: </strong><%= link_to item.code, item %> </p>
<p><strong><%= Item.human_attribute_name(:description) %>:</strong> <%= item.description %> </p>
<p><strong><%= Item.human_attribute_name(:product_category_id) %>: </strong><%= item.product_category.name %> </p>

app/views/items/edit.html.erb
<div>

  <%= render 'shared/form_errors', { obj: @item } %>

  <h3 class="mb-5 ms-4 text-success">Edite as informações do produto:</h3>

  <%= render 'form' %>

</div>

app/views/items/index.html.erb
<div>

  <h3 class="mb-5 ms-4 text-success">Produtos cadastrados</h3>

  <% if @items.any? %>


  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
    <% @items.each do |item| %>
      <div class="col mb-3">
        <div class="card">
          <div class="card border border-success border-opacity-50 rounded-3" id="item_<%= item.id %>">
            <div class="card-body">
              <% if item.image.attached? %>
                <%= image_tag(item.image, class:"img-fluid rounded-start", style:"height: 200px; object-fit: cover;") %>
              <% end %>
              <h5 class="card-title text-success"><strong><%= item.name %></strong></h5>
              <p class="card-text"><%= truncate(item.description, length: 30) %></p>
              <%= link_to 'Ver detalhes', item_path(item), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <% else %>
    <p class="alert alert-warning mt-4" role="alert">Não há produtos cadastrados</p>
  <% end %>

</div>

app/views/items/new.html.erb
<div>

  <%= render 'shared/form_errors', { obj: @item } %>

  <h3 class="mb-5 ms-2 text-success">Cadastre um produto:</h3>

  <%= render 'form' %>

</div>

app/views/items/search.html.erb
<div>

<h3 class="mb-5 ms-2 text-success">Resultado da pesquisa para o termo '<%= @query %>':</h3>

<h4 class="mb-5 ms-2 text-success"><%= @items_code.count %> <%= Item.model_name.human(count: @items_code.count) %> <%= I18n.t(:found, count: @items_code.count) %>:</h4>

<hr>
<% @items_code.each do |item| %>
  <br />
    <%= render item %>
  <br />
    <hr>
  <br />
<% end %>

</div>

app/views/items/show.html.erb
<div>

<div class="card" style="width:100%; height: 100%">
  <div class="row g-0">
    <div class="col-md-4 p-5">
      <% if @item.image.attached? %>
        <%= image_tag(@item.image, class:"img-fluid rounded-start", style:"") %>
      <% end %>
    </div>
    <div class="col-md-8 d-flex align-items-center justify-content-center">
      <div class="card-body">
        <h3 class="card-title mb-4 text-success"> <%= @item.name%></h3>
        <p class="card-text"><strong><%= Item.human_attribute_name(:description) %>: </strong><%= @item.description %></p>
        <p class="card-text"><strong><%= Item.human_attribute_name(:product_category_id) %>: </strong><%= @product_category %></p>
        <p class="card-text"><strong><%= Item.human_attribute_name(:weight) %>: </strong><%= @item.weight %>g</p>
        <p class="card-text"><strong>Dimensões: </strong><%= @item.height %>cm (<%= Item.human_attribute_name(:height).downcase %>) x <%= @item.depth %>cm (<%= Item.human_attribute_name(:depth).downcase %>) x <%= @item.width %>cm (<%= Item.human_attribute_name(:width).downcase %>)</p>
        <p class="card-text"><strong><%= Item.human_attribute_name(:code) %>: </strong><%= @item.code %></p>
        <p class="card-text"><small class="text-body-secondary">Criado em <%= I18n.l(@item.created_at, format: '%d de %B de %Y') %> </small></p>
        <div class="d-flex gap-2">
          <% if current_user.admin? %>
            <%= button_to 'Editar', edit_item_path(@item), method: :get, class: "btn btn-success" %>
          <% end %>
          <%= button_to 'Todos os produtos', items_path, method: :get, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

</div>