config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :lots, only: %i[index show new create edit update] do
    resources :questions, only: %i[new create show] do
      post 'block_by_cpf', on: :member
      resources :answers, only: %i[new create]
      get 'hidden', on: :member
      get 'visible', on: :member
    end
    resources :favorites, only: %i[create destroy]
    resources :bids, only: %i[new create]
    resources :lot_items, only: %i[new create destroy] do
      delete 'remove', on: :member
    end
    get 'expired', on: :collection
    post 'approved', on: :member
    get 'pending', on: :collection
    post 'pending_approval', on: :member
    get 'successfull_bids', on: :collection
    post 'bid_on_lot', on: :member
  end

  resources :product_categories, only: %i[index new create]

  resources :items, only: %i[index new create show edit update] do
    get 'search', on: :collection
  end

  resources :blocked_cpfs, only: %i[index new create]

  resources :users, only: %i[show edit update]

  namespace :api do
    namespace :v1 do
      resources :lots, only: %i[show index create update destroy]
    end
  end
end

app/models/lot.rb
# frozen_string_literal: true

class Lot < ApplicationRecord
  before_save :expired?
  validates :start_date, :limit_date, :minimum_bid_value, :minimum_bid_difference, presence: true

  validates :code, presence: true,
                   uniqueness: true,
                   length: { is: 9 }

  validates :start_date, comparison: { greater_than: :min_date }

  validate :code_format_validation
  validate :bid_value_validation
  validate :bid_value_to_beat
  validate :date_range_validation

  enum status: { pending_approval: 0, approved: 5, ended: 10 }

  # ================ QUESTION ASSOCIATIONS ===========

  has_many :questions
  has_many :users, through: :questions

  # ================ BID ASSOCIATIONS ================

  has_many :bids
  has_many :users, through: :bids

  # ================ LOT_ITEM ASSOCIATIONS ===========

  has_many :lot_items
  has_many :items, through: :lot_items

  # ================ FAVORITES ASSOCIATIONS ===========

  has_many :favorites
  has_many :users, through: :favorites

  # ================ DATES SCOPES =====================

  scope :current, -> { where('start_date <= ? AND limit_date >= ?', Date.today, Date.today) }
  scope :future,  -> { where('start_date > ? AND limit_date > ?', Date.today, Date.today) }
  scope :expired, -> { where('start_date < ? AND limit_date < ?', Date.today, Date.today) }

  after_find :check_expired_status

  def check_expired_status
    return unless expired?

    self.status = :ended unless ended?
  end

  def expired?
    Date.today > limit_date
  end

  def current?
    start_date <= Date.today && limit_date >= Date.today
  end

  def future?
    start_date > Date.today
  end

  # ================ CUSTOM METHODS ===================

  def validate_characters(str)
    str.match?(/\A[a-zA-Z]+\z/)
  end

  def validate_numbers(num)
    num.match?(/\A\d+\z/)
  end

  def code_format_validation
    return if code.empty?

    characters = code.slice(0, 3)
    numbers = code.slice(3, 9)

    return unless !validate_characters(characters) || !validate_numbers(numbers)

    errors.add(:code, message: 'deve ter 3 letras e 6 números')
  end

  def available_items
    Item.where.not(id: LotItem.pluck(:item_id))
  end

  def bid_value_validation
    bid_value = bid_value_to_beat
    if bid_value.present? && bid_value <= minimum_bid_value.to_i
      minimum_bid_value.to_i
    else
      bid_value.to_i
    end
  end

  def bid_value_to_beat
    min_value = minimum_bid_value
    last_bid = bids.last
    if last_bid&.value && last_bid.value >= min_value
      min_value = last_bid.value + minimum_bid_difference
    elsif last_bid&.value && last_bid.value < min_value
      false
    end
    min_value
  end

  def date_range_validation
    return unless start_date.present? && limit_date.present? && start_date >= limit_date

    errors.add(:start_date,
               'deve ser anterior à data limite')
  end

  def successful_bidder
    bl = bids.last
    if bl
      "#{bl.user.name} | #{bl.user.email} | R$#{bl.value},00"
    else
      'Nenhum arrematante para este lote'
    end
  end

  def successful_bidder_name
    bids.last.user.name
  end

  def successful_bidder_email
    bids.last.user.email
  end

  def successful_bidder_value
    "R$#{bids.last.value},00"
  end

  def successful_bidder_lot
    code.upcase
  end

  def successful_bidder_lot_expired_date
    I18n.l(limit_date, format: '%d de %B de %Y')
  end

  def successful_bid_data
    bl = bids.last
    if bl
      "#{bl.user.name} | #{bl.user.email} | R$#{bl.value},00 | Lote #{code.upcase} | Lote expirado em #{I18n.l(
        limit_date, format: '%d de %B de %Y'
      )}"
    else
      "Nenhum lance para o Lote #{code}"
    end
  end

  def min_date
    Time.current
  end
end

app/controllers/api/v1/lots_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class LotsController < Api::V1::ApiController
      def show
        lot = Lot.find(params[:id])
        render status: 200, json: lot.as_json(except: %i[created_at updated_at])
      end

      def index
        lots = Lot.all.order(:code)
        render status: 200, json: lots
      end

      def create
        lot = Lot.new(lot_params)
        if lot.save
          render status: 201, json: lot
        else
          render status: 412, json: { errors: lot.errors.full_messages }
        end
      end

      def update
        lot = Lot.find(params[:id])
        if lot.update(lot_params)
          render status: 200, json: lot
        else
          render status: 412, json: { errors: lot.errors.full_messages }
        end
      end

      def destroy
        lot = Lot.find(params[:id])

        return unless lot.destroy

        render status: 200, json: { message: 'Lote deletado com sucesso' }
      end

      private

      def lot_params
        params.require(:lot).permit(:code,
                                    :start_date,
                                    :limit_date,
                                    :minimum_bid_value,
                                    :minimum_bid_difference,
                                    :by,
                                    :by_email,
                                    :status)
      end
    end
  end
end

app/controllers/lots_controller.rb
# frozen_string_literal: true

class LotsController < ApplicationController
  before_action :set_lot,            only: %i[show approved pending_approval remove edit update bid_on_lot]
  before_action :authenticate_user!, only: %i[new expired pending successfull_bids edit]
  before_action :check_admin_user,   only: %i[new expired pending edit]
  before_action :check_lot_approval, only: [:edit]
  before_action :check_lot_creator,  only: [:edit]

  def index
    redirect_to new_lot_path
  end

  def successfull_bids
    @expired_lots = Lot.expired
  end

  def expired
    @expired_lots = Lot.expired
    @lots = Lot.all
  end

  def pending
    @pending_lots = Lot.pending_approval
    @lots = Lot.all
  end

  def new
    @lot = Lot.new
    @lot_item = LotItem.new
  end

  def create
    @lot = Lot.new(set_params)
    @lot.by = current_user.name
    @lot.by_email = current_user.email
    if @lot.save
      redirect_to @lot, notice: 'Lote cadastrado com sucesso'
    else
      flash.now[:alert] = 'Houve um erro ao cadastrar o lote'
      render :new
    end
  end

  def bid_on_lot
    cpf = current_user.registration_number if user_signed_in?

    if BlockedCpf.where(cpf:, blocked: true).exists?
      flash[:alert] = 'CPF bloqueado. Lance não permitido'
      redirect_to lot_path(params[:id])
    else
      redirect_to new_lot_bid_path(@lot)
    end
  end

  def show
    @expired_lots = Lot.expired
    @question = Question.new
    @questions = @lot.questions
    @favorite = @lot.favorites.where('user_id = ?', current_user&.id).first
  end

  def approved
    @lot.approved_by = current_user.name
    @lot.approved_by_email = current_user.email
    @lot.approved!
    redirect_to @lot
  end

  def pending_approval
    @lot.pending_approval!
    redirect_to @lot
  end

  def remove
    @lot_item = @lot.lot_items.find(params[:id])
  end

  def edit; end

  def update
    if @lot.update(set_params)
      redirect_to @lot, notice: 'Lote atualizado com sucesso'
    else
      flash.now[:alert] = 'Houve um problema ao atualizar o lote'
      render 'edit'
    end
  end

  private

  def set_lot
    @lot = Lot.find(params[:id])
  end

  def set_params
    params.require(:lot).permit(:code,
                                :start_date,
                                :limit_date,
                                :minimum_bid_value,
                                :minimum_bid_difference,
                                :by,
                                :by_email,
                                :status)
  end

  def check_admin_user
    return if current_user.admin?

    redirect_to root_path, alert: 'Você não tem permissão para acessar esta página'
  end

  def check_lot_approval
    return if @lot.pending_approval?

    redirect_to @lot, alert: 'Lote já aprovado'
  end

  def check_lot_creator
    return if @lot.by_email == current_user.email

    redirect_to @lot, alert: 'Apenas o autor do lote pode editá-lo'
  end

  def favorite_option(lot)
    # @favorite = Favorite.new
    # return unless user_signed_in? && current_user.favorite_lots&.include?(lot)

    @favorite = current_user.favorites.find { |fav| fav.lot_id == lot.id }
  end
end

app/views/lots/edit.html.erb
<div class="mx-auto p-4" style="width: 75%; background: #e9ecef">

<%= render 'shared/form_errors', { obj: @lot } %>

  <h2>Atualize o lote</h2>

    <%= form_with model: @lot, local: true do |f|  %>

      <div class="input-group input-group-lg mt-4">
        <%= f.label :code, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-lg" %><br />
        <%= f.text_field :code, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-lg", autofocus: true %>
      </div>

      <div class="input-group input-group-lg mt-4">
        <%= f.label :start_date, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-lg"  %><br />
        <%= f.date_field :start_date, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-lg" %>
      </div>

      <div class="input-group input-group-lg mt-4">
        <%= f.label :limit_date, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-lg"  %><br />
        <%= f.date_field :limit_date, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-lg" %>
      </div>

      
      <div class="input-group input-group-lg mt-4">
        <%= f.label :minimum_bid_value, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-lg"   %><br />
        <%= f.number_field :minimum_bid_value, placeholder: 'Insira apenas números', class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-lg", autofocus: true %>
      </div>

      <div class="input-group input-group-lg mt-4">
        <%= f.label :minimum_bid_difference, class: "input-group-text fw-bold w-25", id: "inputGroup-sizing-lg"  %><br />
        <%= f.number_field :minimum_bid_difference, placeholder: 'Insira apenas números', class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-lg", autofocus: true%> 
      </div>

      <div class="d-grid">
        <%= f.submit 'Salvar', class: "btn btn-success mb-3 mt-5 btn-lg" %>
      </div>

    <% end %>

</div>

app/views/lots/expired.html.erb
<div>

<h3 class="mb-5 ms-4 text-success">Lotes expirados</h3>

<h3><%= 'Nenhum lote expirado' if @expired_lots.empty? %></h3>
<div class="row">

  <% if @expired_lots.any? %>

    <% @expired_lots.each do |lot| %>

      <div class="col mb-3" style="width: 20rem;">
        <div class="card">
          <div class="card border border-secondary border-opacity-50 rounded-3">
            <div class="card-body">
              <h6 class="card-title">Lote encerrado em:</h6>
              <p class="card-text"><%= I18n.l(lot.limit_date) %></p>
              <%= link_to "#{lot.code}", lot_path(lot), class: "btn btn-danger mb-3 mt-2"  %>
            </div>
          </div>
        </div>
      </div>

    <% end %>

  <% end %>
</div>

app/views/lots/new.html.erb
<%= stylesheet_link_tag 'custom' %>
<div>

  <%= render 'shared/form_errors', { obj: @lot } %>

  <h3 class="mb-5 ms-2 text-success">Criar um novo lote</h3>

    <%= form_with model: @lot, data: { turbo: false }, local: true do |f|  %>

      <div class="input-group input-group-default mt-4">
        <%= f.label :code, class: "input-group-text fw-bold col-md-3 media-breakpoint-up(md)", id: "inputGroup-sizing-default" %><br />
        <%= f.text_field :code, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-lg", autofocus: true %>
      </div>

      <div class="input-group input-group-default mt-4">
        <%= f.label :start_date, class: "input-group-text fw-bold col-md-3 media-breakpoint-up(md)", id: "inputGroup-sizing-default"  %><br />
        <%= f.date_field :start_date, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
      </div>

      <div class="input-group input-group-default mt-4">
        <%= f.label :limit_date, class: "input-group-text fw-bold col-md-3", id: "inputGroup-sizing-default"  %><br />
        <%= f.date_field :limit_date, class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default" %>
      </div>


      <div class="input-group input-group-default mt-4">
        <%= f.label :minimum_bid_value, class: "input-group-text fw-bold col-md-3", id: "inputGroup-sizing-default"   %><br />
        <%= f.number_field :minimum_bid_value, placeholder: 'Insira apenas números', class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default", autofocus: true %>
      </div>

      <div class="input-group input-group-default mt-4">
        <%= f.label :minimum_bid_difference, class: "input-group-text fw-bold col-md-3", id: "inputGroup-sizing-default"  %><br />
        <%= f.number_field :minimum_bid_difference, placeholder: 'Insira apenas números', class: "form-control", aria_label: "Sizing example input", aria_describedby: "inputGroup-sizing-default", autofocus: true%>
      </div>

      <div class="d-grid">
        <%= f.submit 'Cadastrar lote', class: "btn btn-success mb-3 mt-5 btn-default" %>
      </div>

    <% end %>

</div>

app/views/lots/pending.html.erb
  <div>
  <h3 class="mb-5 ms-4 text-success">Lotes pendentes</h3>

  <h3><%= 'Nenhum lote cadastrado' if @pending_lots.empty? %></h3>

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
    <% if current_user && current_user.admin? %>
      <% if @pending_lots.any? %>
        <% @pending_lots.each do |lot| %>
          <% if lot.pending_approval? %>
            <div class="col mb-3">
              <div class="card">
                <div class="card border border-secondary border-opacity-50 rounded-3">
                  <div class="card-body">
                    <h6 class="card-title">Previsão de abertura:</h6>
                    <p class="card-text"><%= I18n.l(lot.start_date) %></p>
                    <%= link_to "#{lot.code}", lot_path(lot), class: "btn btn-warning mb-3 mt-2"  %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lots/show.html.erb
<div>

  <h3 class="mb-5 text-success"><%= Lot.model_name.human %> <%= @lot.code.upcase %></h3>

  <div class="d-flex gap-2" %>
    <% if @lot.approved? && @lot.current? && user_signed_in? && !current_user.admin? %>
        <%= button_to "Fazer um lance a partir de R$#{@lot.bid_value_to_beat},00",
                bid_on_lot_lot_path(@lot.id),
                method: :post,
                class: "btn btn-primary mb-3 mt-2 me-2" %>

        <% if current_user.favorites.any? { |fav| fav.lot_id == @lot.id } %>
          <%= link_to 'Remover dos favoritos', lot_favorite_path(@lot, @favorite), data: { turbo_method: :delete }, class: "btn btn-secondary mb-3 mt-2 me-2" %>
        <% else %>
          <%= form_with model: @favorite, url: lot_favorites_path(@lot) do |f| %>
            <%= f.hidden_field :lot_id, value: @lot.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.submit "Marcar lote como favorito", class: "btn btn-success mb-3 mt-2 me-2" %>
          <% end %>
        <% end %>
      <% else %>
        <% if !@lot.expired? %>
          <%= button_to "Lances para lotes ativos e usuários comuns logados",
                  bid_on_lot_lot_path(@lot.id),
                  method: :post,
                  class: "btn btn-secondary mb-3 mt-2 me-2",
                  disabled: true %>
        <% end %>
    <% end %><br />
  </div>


  <% if @lot.expired? && @lot.bids.count == 0 %>
    <h3 class="bg-danger text-white" style="--bs-text-opacity: .75; padding: 1rem">Cancelado por falta de lances</h3><br />
  <% elsif @lot.expired? && @lot.bids.count >= 1 %>
    <h3 class="bg-success text-white" style="--bs-text-opacity: .75; padding: 1rem"><strong>Arrematante: </strong><%= @lot.successful_bidder %></h3><br />
  <% end %>

  <table class="table table-success table-striped mb-5">
     <tbody>
      <tr>
        <td><strong><%= Lot.human_attribute_name(:code) %></strong></td>
        <td><%= @lot.code.upcase %></td>
      </tr>
      <tr>
        <td><strong><%= Lot.human_attribute_name(:start_date) %></strong></td>
        <td><%= I18n.l(@lot.start_date) %></td>
      </tr>
      <tr>
        <td><strong><%= Lot.human_attribute_name(:limit_date) %></strong></td>
        <td><%= I18n.l(@lot.limit_date) %></td>
      </tr>
      <tr>
        <td><strong><%= Lot.human_attribute_name(:minimum_bid_value) %> inicial</strong></td>
        <td>R$<%= @lot.minimum_bid_value %>,00 </td>
      </tr>
      <tr>
        <td><strong><%= Lot.human_attribute_name(:minimum_bid_difference) %></strong></td>
        <td>R$<%= @lot.minimum_bid_difference %>,00 </td>
      </tr>
      <% if !@lot.expired? %>
        <tr>
          <td><strong><%= Lot.human_attribute_name(:minimum_bid_value) %> atual</strong>
          <td>R$<%= @lot.bid_value_to_beat %>,00 </td>
        </tr>
      <% end %>
      <% if !@lot.expired? || !@lot.current? %>
        <tr>
          <td><strong>Lances feitos:</strong></td>
          <td><%= @lot.bids.count %></td>
        </tr>
      <% end %>
      <% if @lot.pending_approval? %>
        <tr>
          <td class="text-danger"><strong>Situação</strong></td>
          <td class="text-danger">Aguardando aprovação</td>
        </tr>
      <% elsif @lot.expired? %>
        <tr>
          <td class="text-danger"><strong>Situação</strong></td>
          <td class="text-danger">Lote expirado</td>
        </tr>
      <% elsif @lot.approved? %>
        <tr>
          <td class="text-primary"><strong>Situação</strong></td>
          <td class="text-primary">Lote aprovado</td>
        </tr>
      <% end %>
     </tbody>
  </table>


  <% if !@lot.approved? && @lot.future? %>
    <div>
      <%= link_to 'Adicionar item', new_lot_lot_item_path(lot_id: @lot.id) %>
    </div><br />
  <% end %>

  <% if @lot.lot_items.any? %>
    <div class="mb-4">
      <h4 class="mb-2"><strong>Itens do lote:</strong></h4>

      <% @lot.lot_items.each do |item| %>
        <div class="lot-items d-flex align-items-center gap-3">
          <p class="mt-3"><strong><%= item.item.name %></strong> - cód. <%= item.item.code %></p>
          <% if !@lot.approved? %>
            <%= button_to 'Remover', remove_lot_lot_item_path(@lot, item), method: :delete, class: "btn btn-light" %>
            <%= button_to 'Detalhes', item_path(item.id), method: :get, class: "btn btn-light" %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <span class="align-items-center">
    <% if user_signed_in? && current_user.admin? %>
     <hr><br />
      <p><strong>Criado por:</strong> <%= @lot.by %> | <%= @lot.by_email %></p>

      <% if current_user.email != @lot.by_email %>

        <% if @lot.pending_approval? && !@lot.expired? %>
          <div class="d-inline-flex ">
            <%= button_to "Aprovar lote", approved_lot_path(@lot.id), class: "btn btn-success mb-3 mt-2 me-2"%>
          </div>
        <% else %>
          <p><strong>Aprovado por:</strong> <%= @lot.approved_by %> | <%= @lot.approved_by_email %></p>
        <% end %>

      <% end %>
       <br /><hr><br />
    <% end %>
  </span>


  <div>
  <div>
  <% if !@lot.expired? %>

    <% if user_signed_in? && !current_user.admin? %>

      <h3>Tem alguma dúvida? Pergunte aqui:</h3><br />

      <%= form_with(model: [@lot, @question], url: block_by_cpf_lot_question_path(@lot), method: :post) do |f| %>
        <div class="d-flex">
          <%= f.text_area :body, class: "form-control", style: "width: 30vw;", placeholder: 'Escreva aqui' %>
        </div>
        <div >
          <%= f.submit 'Enviar', class: 'btn btn-primary mt-2'%>
        </div>
      <% end %>
    <% end %>


    <% if @questions.any? %>
      <% @questions.each do |question| %>
        <br />
          <div class="d-flex gap-2">
            <p><i><%= I18n.l(question.created_at, format: '%d de %B de %Y') %> - Usuário(a): <%= question.user.name %></i></p>
            <% if question.user.image.attached? %>
              <%= image_tag url_for(question.user.image), alt: question.user.name, class: 'rounded-circle', size: '30x30' %>
            <% end %>
          </div>
          <div class="d-flex gap-2">
            <% if question.visible? %>
                <p><strong><%= question.body %></strong></p><br />
            <% else %>
                <p class="ms-5 text-secondary text-opacity: .5"><i>Esta pergunta fere as normas do site</i></p>
            <% end %>
            <% if user_signed_in? && current_user.admin? %>
              <% if question.visible? %>
                <p><%= link_to 'Ocultar', hidden_lot_question_path(@lot, question) %></p>
              <% else %>
                <p><%= link_to 'Tornar visível', visible_lot_question_path(@lot, question) %></p>
              <% end %>
            <% end %>
          </div>

          <% if question.answers.any? && question.visible? %>
            <% question.answers.each do |answer| %>
              <div class="ms-5 d-flex flex-column gap-2">
                <div class="d-flex gap-2">
                  <% if answer.created_at %>
                    <p><i><%= I18n.l(answer.created_at, format: '%d de %B de %Y') %> - Admin: <%= answer.user.name %></i></p>
                  <% end %>
                  <% if current_user.image.attached? %>
                    <%= image_tag url_for(answer.user.image), alt: current_user.name, class: 'rounded-circle', size: '30x30' %>
                  <% end %>

                </div>

                <p><i><strong><%= answer.reply %></strong></i></p><br />
              </div>
            <% end %>
          <% end %>
          <% if user_signed_in? && current_user.admin? && question.visible? %>
            <%= form_with(model: [@lot, question, question.answers.build]) do |f| %>
              <div>
                <%= f.text_area :reply, class: "form-control bg-secondary bg-opacity-10", style: "width: 30vw;", placeholder: 'Responda aqui' %>
              </div>
              <div>
                <%= f.submit 'Responder', class: 'btn btn-warning mt-2' %>
              </div>
            <% end %>
          <% end %>


      <% end %>
    <% else %>
        <p><i>Nenhuma pergunta</i></p>
    <% end %>
  <% end %>
  <div class="d-flex gap-1">
    <%= link_to 'Tela inicial', root_path, class: "btn btn-success mb-3 mt-2 me-2"  %>
    <% if user_signed_in? && current_user.admin? %>
      <% if @lot.pending_approval?  %>
        <%= link_to 'Editar lote', edit_lot_path(@lot), class: "btn btn-success mb-3 mt-2 me-2"  %>
      <% elsif @lot.approved? %>
        <p>
          <button class="btn btn-secondary mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-message" aria-expanded="false" aria-controls="collapseExample">
            Editar lote
          </button>
        </p>
        <div class="collapse" id="collapse-message">
          <div class="card card-body bg-transparent">
            Lote já aprovado
          </div>
        </div>
      <% end %>
    <% end %>
  <div>


</div>

app/views/lots/successfull_bids.html.erb
<div>

<h2 class="mb-5 ms-2 text-success">Lances vencedores:</h2>



<% if @expired_lots.any?  %>

<%# ====================== INÍCIO DA TABELA ============================= %>

      <table class="table table-success table-striped">
        <thead>
          <tr>
            <th scope="col">Arrematante</th>
            <th scope="col">Email</th>
            <th scope="col">Valor</th>
            <th scope="col">Lote</th>
            <th scope="col">Expirado em</th>
          </tr>
        </thead>
        <tbody>

  <% @expired_lots.each do |lot| %>

    <% if lot.bids.any? %>


          <tr>
            <th scope="row"><%= lot.successful_bidder_name %></th>
            <td><%= lot.successful_bidder_email %></td>
            <td><%= lot.successful_bidder_value %></td>
            <td><%= lot.successful_bidder_lot %></td>
            <td><%= lot.successful_bidder_lot_expired_date %></td>
          </tr>


    <% end %>

  <% end %>
  <%# ====================== FIM DA TABELA: ============================= %>
         </tbody>
      </table>
  <% else %>

    <h3><%= 'Nenhum lance vencedor' %></h3>

<% end %>

</div>