config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :lots, only: %i[index show new create edit update] do
    resources :questions, only: %i[new create show] do
      post 'block_by_cpf', on: :member
      resources :answers, only: %i[new create]
      get 'hidden', on: :member
      get 'visible', on: :member
    end
    resources :favorites, only: %i[create destroy]
    resources :bids, only: %i[new create]
    resources :lot_items, only: %i[new create destroy] do
      delete 'remove', on: :member
    end
    get 'expired', on: :collection
    post 'approved', on: :member
    get 'pending', on: :collection
    post 'pending_approval', on: :member
    get 'successfull_bids', on: :collection
    post 'bid_on_lot', on: :member
  end

  resources :product_categories, only: %i[index new create]

  resources :items, only: %i[index new create show edit update] do
    get 'search', on: :collection
  end

  resources :blocked_cpfs, only: %i[index new create]

  resources :users, only: %i[show edit update]

  namespace :api do
    namespace :v1 do
      resources :lots, only: %i[show index create update destroy]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name registration_number image about])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name registration_number image about])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="bg-success d-flex flex-column align-items-center justify-content-center gap-2 mt-4 p-4 text-white">
  <p>Feito com amor em BH/MG/Brasil</p>
  <p>Ricardo Novais</p>
</footer>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary d-flex justify-content-between gap-4">
          <div class="container-fluid d-flex justify-content-between gap-5">
            <%= link_to root_path, class: 'navbar-brand' do %>
                <%= image_tag('Legal-1.png', alt: 'Logo do Site', class: 'logo', style: 'width: 5rem; height: auto;') %>
            <% end %>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item dropdown custom-nav-item">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Menu
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'Home', root_path, class: 'nav-link', 'aria-current': 'page'%></li>
                        <li><%= link_to 'Produtos', items_path, class: 'nav-link', 'aria-current': 'page' %></li>
                        <li><%= link_to 'Arrematantes', successfull_bids_lots_path, class: 'nav-link', 'aria-current': 'page' %></li>
                      </ul>
                  </li>
                <% if user_signed_in? %>
                  <% if current_user.admin? %>
                    <li class="nav-item dropdown custom-nav-item">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Administrativo
                      </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to 'Categorias de produto', new_product_category_path, class: 'dropdown-item link-secondary custom-nav-item' %></li>
                          <li><%= link_to 'Criar lote', new_lot_path, class: 'dropdown-item link-secondary custom-nav-item' %></li>
                          <li><%= link_to 'Novo produto', new_item_path, class: 'dropdown-item link-secondary custom-nav-item' %></li>
                          <li><%= link_to 'Lotes pendentes',pending_lots_path, class: 'dropdown-item link-secondary custom-nav-item' %></li>
                          <li><%= link_to 'Lotes expirados', expired_lots_path, class: 'dropdown-item link-secondary custom-nav-item' %></li>
                          <li><%= link_to 'Bloquear CPF', new_blocked_cpf_path, class: 'dropdown-item link-secondary custom-nav-item' %></li>
                        </ul>
                  </li>
                  <% end %>
                  <li class="sair nav-item ms-auto custom-nav-item">
                    <%= link_to 'Sair', destroy_user_session_path, 'data-turbo-method': :delete, class: "nav-link text-decoration-none text-secondary" %>
                  </li>
                  <% if current_user.image.attached? %>
                    <li class="nav-item nav-link link-success user-image">
                      <%= image_tag url_for(current_user.image), alt: current_user.name, class: 'rounded-circle', size: '25x25' %>
                    </li>
                  <% end %>
                  <li class="nav-item nav-link link-secondary">
                    <span><p class="custom-nav-item">Olá <%= current_user.user_first_name %>!</p></span>
                  </li>
                  <li class="nav-item nav-link link-secondary">
                    <span><p class="custom-nav-item"><%= link_to 'Meu perfil', user_path(current_user.id), class: "text-decoration-none link-secondary" %></p></span>
                  </li>
                <% else %>
                  <li class="nav-item custom-nav-item">
                    <%= link_to 'Entrar/ Cadastrar', new_user_session_path, class: "nav-link text-decoration-none text-secondary" %>
                  </li>
                <% end %>
              </ul>
              <%= form_with(url: search_items_path, method: :get, html: { class: "d-flex" }) do |f| %>
                <%= f.text_field :query, class: "form-control me-2 custom-nav-item search-field-width", placeholder: "Buscar produto" %>
                <%= f.submit 'Buscar', class: "btn btn-outline-success custom-nav-item" %>
              <% end %>
            </div>
          </div>
      </nav>

app/views/application/_navdouble.html.erb
<div class="d-flex flex-column">
  <nav class="navbar navbar-expand-lg bg-body-tertiary gap-4">
    <div class="container-fluid">
      <div class="d-flex justify-content-around align-items-center">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag('Legal-1.png', alt: 'Logo do Site', class: 'logo', style: 'width: 5rem; height: auto;') %>
        <% end %>

        <div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <% if user_signed_in? %>
                <% if current_user.admin? %>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Administrativo
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Categorias de produto', new_product_category_path, class: 'dropdown-item link-secondary' %></li>
                      <li><%= link_to 'Criar lote', new_lot_path, class: 'dropdown-item link-secondary' %></li>
                      <li><%= link_to 'Novo produto', new_item_path, class: 'dropdown-item link-secondary' %></li>
                      <li><%= link_to 'Lotes pendentes', pending_lots_path, class: 'dropdown-item link-secondary' %></li>
                      <li><%= link_to 'Lotes expirados', expired_lots_path, class: 'dropdown-item link-secondary' %></li>
                      <li><%= link_to 'Bloquear CPF', new_blocked_cpf_path, class: 'dropdown-item link-secondary' %></li>
                    </ul>
                  </li>
                <% end %>
                <li class="nav-item nav-link link-success">
                  <%= current_user.email %>
                </li>
                <% if current_user.image.attached? %>
                  <li class="nav-item nav-link link-success">
                    <%= image_tag url_for(current_user.image), alt: current_user.name, class: 'rounded-circle', size: '30x30' %>
                  </li>
                <% end %>
                <li class="nav-item nav-link link-secondary">
                  <span><p>Olá <%= current_user.user_first_name %>!</p></span>
                </li>
                <li class="nav-item nav-link link-secondary">
                  <%= link_to 'Meu perfil', user_path(current_user.id), class: 'text-decoration-none link-secondary' %>
                </li>
                <li class="sair nav-item">
                  <%= link_to 'Sair', destroy_user_session_path, 'data-turbo-method': :delete, class: "nav-link text-decoration-none text-secondary" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Entrar/ Cadastrar', new_user_session_path, class: "nav-link text-decoration-none text-secondary" %>
                </li>
          <% end %>
        </ul>
        </div>
      </nav>
        <%#  %>
      <nav class="navbar navbar-expand-lg bg-body-tertiary gap-4">
          <ul class="navbar-nav d-flex justify-content-between me-auto mb-2 mb-lg-0" style="width: 100%">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link', 'aria-current': 'page' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Produtos', items_path, class: 'nav-link', 'aria-current': 'page' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Arrematantes', successfull_bids_lots_path, class: 'nav-link', 'aria-current': 'page' %>
            </li>
            <%= form_with(url: search_items_path, method: :get, html: { class: "d-flex" }) do |f| %>
              <%= f.text_field :query, class: "form-control me-2", placeholder: "Buscar produto" %>
              <%= f.submit 'Buscar', class: "btn btn-outline-success" %>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</nav>
</div>